DWAPlannerROS:
# Robot Configuration Parameters
  max_vel_x: 0.5   # x方向最大线速度绝对值，单位:m/s
  min_vel_x: -0.5   # x方向最小线速度绝对值，负数代表可后退，单位:m/s
 
  max_vel_y: 0.5   # y方向最大线速度绝对值，单位:m/s
  min_vel_y:  -0.5    # y方向最小线速度绝对值，负数代表可后退，单位:m/s
 
  max_vel_trans: 0.5 #1.3    # 机器人最大平移速度的绝对值，单位为:m/s
  min_vel_trans: 0.08    # 机器人最小平移速度的绝对值，单位为:m/s（不可为零）
 
  max_vel_theta: 0.0 # 0.1     # 机器人的最大旋转角速度的绝对值，单位为:rad/s 
  min_vel_theta: 0.0  # 器人的最小旋转角速度的绝对值，单位为:rad/s
 
  acc_lim_x: 10    # 机器人在x方向的极限加速度，单位为:m/s^2
  acc_lim_y: 10    # 机器人在y方向的极限加速度，单位为:m/s^2
  acc_lim_theta: 0    # 机器人的极限旋转加速度，单位为:rad/s^2
  
# Goal Tolerance Parametes
  xy_goal_tolerance: 0.1    # 到到目标点时，控制器在x和y方向上的容差（m）
  yaw_goal_tolerance: 3.14    # 到达目标点时，控制器在偏航/旋转时的弧度容差（rad）
  latch_xy_goal_tolerance: false    # 设置为true时表示：如果到达容错距离内，机器人就会原地旋转
 
# Forward Simulation Parameters
  sim_time: 2    # 前向模拟轨迹的时间，单位为s
  vx_samples: 20    # x方向速度空间的采样点数
  vy_samples: 20    # y方向速度空间的采样点数
  vth_samples: 40    # 旋转方向的速度空间采样点数
  controller_frequency: 5.0
 
# Trajectory Scoring Parameters
  path_distance_bias: 40 #60.0    # 控制器与给定路径接近程度的权重
  goal_distance_bias: 15 #15.0    # 控制器与局部目标点的接近程度的权重，也用于速度控制
  occdist_scale: 0.05   # 控制器躲避障碍物的程度
  forward_point_distance: 0.325    # 以机器人为中心，额外放置一个计分点的距离
  stop_time_buffer: 0.2     # 机器人在碰撞发生前必须拥有的最少时间量
  scaling_speed: 0.25    # 开始缩放机器人足迹时的速度的绝对值，单位为m/s
  max_scaling_factor: 0.2    # 最大缩放因子
 
# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05    # 机器人必须运动多少米远后才能复位震荡标记
# Debugging
  publish_traj_pc : true    # 将规划的轨迹在RVIZ上进行可视化
  publish_cost_grid_pc: true    # 将代价值进行可视化显示