GlobalPlanner:
  # 是否使用D*全局规划算法，默认为true，如果为false，则使用A*算法
  use_dijkstra: True
  # 是否沿着网格规划路径，默认为false，false时使用最速下降法计算路径
  use_grid_path: False
  # 是否使用二次逼近的趋势，默认为true，否则使用简单的线性方法
  use_quadratic: True